/*!
* Tarot Carousel v0.1.0 (beta)
* A highly customizable carousel with beautiful, physics-driven animations
* Copyright 2026 Magic Spells LLC
*
* This software is source-available but not open source. Licensed under:
*   - Magic Spells Non-Commercial License (free for personal / non-revenue projects)
*   - Magic Spells Commercial License (commercial use, entities under $1M revenue)
*   - Magic Spells Enterprise License (all use by entities with $1M+ revenue)
*
* Author: Cory Schulz
* Website: https://www.magicspells.io/tarot
* Repo: https://github.com/magic-spells/tarot
* Licenses: https://www.magicspells.io/licenses
*/
//#region src/scrollbar.js
/**
* Scrollbar Plugin
* Displays a proportional thumb scrollbar for carousel navigation
*
* Features:
* - Proportional thumb width based on page count
* - Real-time bidirectional sync with carousel track position
* - Drag thumb to scrub through carousel
* - Click track to navigate to nearest page
* - Keyboard navigation (arrows, Home, End)
* - Settle-on-release based on snap mode (page, slide, none)
*
* Mounts only on explicit opt-in (`scrollbar: { show: true }`): while disabled
* the plugin keeps a single options:changed watcher and nothing else — no DOM,
* no per-frame listeners.
*
* Spatial progress (`animation.trackPercent`) is maintained by the store, so the
* scrollbar reads it directly instead of recomputing track geometry.
*/
var MIN_THUMB_WIDTH_PX = 24;
var DRAG_CLICK_THRESHOLD_PX = 3;
var DRAG_CLICK_SUPPRESSION_MS = 120;
var Scrollbar = class {
	static pluginName = "scrollbar";
	static defaultOptions = { scrollbar: {
		show: false,
		selector: false
	} };
	#targetPercent = 0;
	#lastSyncedPercent = -1;
	#rafId = null;
	#didMeaningfulDrag = false;
	#lastDragEndTs = 0;
	#thumbWidthPercent = 0;
	#maxTravelPercent = 100;
	constructor(ctx) {
		const _ = this;
		_.ctx = ctx;
		_.scrollbarOptions = {};
		_.enabled = false;
		_.scrollbarContainer = null;
		_.scrollbarTrack = null;
		_.scrollbarThumb = null;
		_.scrollbarGhost = null;
		_.isAutoGenerated = false;
		_.isDragging = false;
		_.dragStartX = 0;
		_.dragStartPercent = 0;
		_.activePointerId = null;
		_.pointerCaptureTarget = null;
		_.handlers = {
			trackPositionChanged: (payload) => _.handleTrackPositionChanged(payload),
			optionsChanged: () => _.reInit(),
			layoutChanged: () => _.reInit(),
			pageCountChanged: () => _.reInit(),
			pageIndexChanged: () => _.updateAriaValues(),
			movementCompleted: () => _.handleMovementCompleted(),
			pointerDown: (event) => _.startDrag(event),
			pointerMove: (event) => _.handleDrag(event),
			pointerUp: (event) => _.endDrag(event),
			pointerCancel: (event) => _.endDrag(event),
			lostPointerCapture: (event) => _.handleLostPointerCapture(event),
			touchStart: (event) => _.handleTouchStart(event),
			touchMove: (event) => _.handleTouchMove(event),
			trackClick: (event) => _.handleTrackClick(event),
			keyDown: (event) => _.handleKeyDown(event)
		};
		_.init();
	}
	init() {
		const _ = this;
		_.scrollbarOptions = _.ctx.store.getOptions().scrollbar || {};
		_.enabled = !!_.scrollbarOptions.show;
		_.ctx.emitter.on(_.ctx.events.store.optionsChanged, _.handlers.optionsChanged);
		if (_.enabled) _.mount();
	}
	reInit() {
		const _ = this;
		const previousSelector = _.scrollbarOptions.selector;
		const wasEnabled = _.enabled;
		_.scrollbarOptions = _.ctx.store.getOptions().scrollbar || {};
		_.enabled = !!_.scrollbarOptions.show;
		if (_.enabled && !wasEnabled) _.mount();
		else if (!_.enabled && wasEnabled) _.unmount();
		else if (_.enabled && _.scrollbarOptions.selector !== previousSelector) {
			_.unmount();
			_.mount();
		} else if (_.enabled) _.render();
	}
	/** build the scrollbar DOM, bind its listeners and draw the first frame */
	mount() {
		const _ = this;
		_.queryDOM();
		_.bindEvents();
		_.render();
	}
	/** tear down everything mount() created — drag state, listeners and DOM */
	unmount() {
		const _ = this;
		_.stopDrag();
		_.unbindEvents();
		_.removeDOM();
	}
	queryDOM() {
		const _ = this;
		if (_.scrollbarOptions.selector) {
			const element = document.querySelector(_.scrollbarOptions.selector);
			if (element) _.scrollbarContainer = element;
		}
		if (!_.scrollbarContainer) {
			_.isAutoGenerated = true;
			_.scrollbarContainer = document.createElement("div");
			_.ctx.carousel.appendChild(_.scrollbarContainer);
		}
		_.scrollbarContainer.classList.add("tarot-scrollbar");
		const carouselID = _.ctx.carousel.id;
		_.removeOwnedTrackNodes();
		_.scrollbarTrack = document.createElement("div");
		_.scrollbarTrack.classList.add("tarot-scrollbar-track");
		_.scrollbarTrack.setAttribute("data-tarot-scrollbar-owned", "true");
		_.scrollbarTrack.setAttribute("data-tarot-scrollbar-owner", carouselID);
		_.scrollbarContainer.appendChild(_.scrollbarTrack);
		_.scrollbarThumb = document.createElement("div");
		_.scrollbarThumb.classList.add("tarot-scrollbar-thumb");
		_.scrollbarThumb.setAttribute("role", "slider");
		_.scrollbarThumb.setAttribute("tabindex", "0");
		_.scrollbarThumb.setAttribute("aria-label", "Navigation thumb");
		_.scrollbarThumb.setAttribute("aria-valuemin", "0");
		_.scrollbarThumb.setAttribute("aria-controls", carouselID);
		_.scrollbarTrack.appendChild(_.scrollbarThumb);
		_.scrollbarGhost = document.createElement("div");
		_.scrollbarGhost.classList.add("tarot-scrollbar-ghost");
		_.scrollbarGhost.setAttribute("aria-hidden", "true");
		_.scrollbarTrack.appendChild(_.scrollbarGhost);
	}
	/** subscribe while mounted (optionsChanged is bound for the whole lifetime) */
	bindEvents() {
		const _ = this;
		const { emitter, events } = _.ctx;
		emitter.on(events.track.positionChanged, _.handlers.trackPositionChanged);
		emitter.on(events.store.layoutChanged, _.handlers.layoutChanged);
		emitter.on(events.store.pageCountChanged, _.handlers.pageCountChanged);
		emitter.on(events.store.pageIndexChanged, _.handlers.pageIndexChanged);
		emitter.on(events.movement.completed, _.handlers.movementCompleted);
		_.scrollbarTrack.addEventListener("pointerdown", _.handlers.pointerDown, { passive: false });
		_.scrollbarTrack.addEventListener("pointercancel", _.handlers.pointerCancel, { passive: false });
		_.scrollbarTrack.addEventListener("touchstart", _.handlers.touchStart, { passive: false });
		_.scrollbarTrack.addEventListener("touchmove", _.handlers.touchMove, { passive: false });
		_.scrollbarTrack.addEventListener("click", _.handlers.trackClick);
		_.scrollbarThumb.addEventListener("keydown", _.handlers.keyDown);
		_.scrollbarThumb.addEventListener("lostpointercapture", _.handlers.lostPointerCapture);
		_.scrollbarGhost.addEventListener("lostpointercapture", _.handlers.lostPointerCapture);
	}
	/** mirror of bindEvents — leaves the always-on optionsChanged watcher alone */
	unbindEvents() {
		const _ = this;
		const { emitter, events } = _.ctx;
		emitter.off(events.track.positionChanged, _.handlers.trackPositionChanged);
		emitter.off(events.store.layoutChanged, _.handlers.layoutChanged);
		emitter.off(events.store.pageCountChanged, _.handlers.pageCountChanged);
		emitter.off(events.store.pageIndexChanged, _.handlers.pageIndexChanged);
		emitter.off(events.movement.completed, _.handlers.movementCompleted);
		if (!_.scrollbarTrack) return;
		_.scrollbarTrack.removeEventListener("pointerdown", _.handlers.pointerDown);
		_.scrollbarTrack.removeEventListener("pointercancel", _.handlers.pointerCancel);
		_.scrollbarTrack.removeEventListener("touchstart", _.handlers.touchStart);
		_.scrollbarTrack.removeEventListener("touchmove", _.handlers.touchMove);
		_.scrollbarTrack.removeEventListener("click", _.handlers.trackClick);
		_.scrollbarThumb.removeEventListener("keydown", _.handlers.keyDown);
		_.scrollbarThumb.removeEventListener("lostpointercapture", _.handlers.lostPointerCapture);
		_.scrollbarGhost.removeEventListener("lostpointercapture", _.handlers.lostPointerCapture);
	}
	removeOwnedTrackNodes() {
		const _ = this;
		const carouselID = _.ctx.carousel.id;
		_.scrollbarContainer.querySelectorAll(":scope > .tarot-scrollbar-track").forEach((track) => {
			if (track.getAttribute("data-tarot-scrollbar-owned") !== "true") return;
			const owner = track.getAttribute("data-tarot-scrollbar-owner");
			if (owner && owner !== carouselID) return;
			track.remove();
		});
	}
	render() {
		const _ = this;
		if (_.ctx.store.getState().pageCount <= 1) {
			_.hide();
			return;
		}
		_.show();
		_.updateThumbSize();
		_.updateAriaValues();
		_.syncToTrackPercent(_.ctx.store.getAnimation().trackPercent);
	}
	syncToTrackPercent(trackPercent) {
		const _ = this;
		const canLoop = _.ctx.store.getState().canLoop;
		if (canLoop && trackPercent > 1) {
			_.activateGhost();
			_.updatePortalForward(trackPercent - 1);
		} else if (canLoop && trackPercent < 0) {
			_.activateGhost();
			_.updatePortalBackward(Math.abs(trackPercent));
		} else {
			_.deactivateGhost();
			_.updateThumbPosition(trackPercent);
		}
	}
	handleTrackPositionChanged(payload) {
		if (this.isDragging) return;
		this.syncToTrackPercent(payload.trackPercent);
	}
	handleMovementCompleted() {
		const _ = this;
		if (_.isDragging) return;
		_.syncToTrackPercent(_.ctx.store.getAnimation().trackPercent);
	}
	updateThumbSize() {
		const _ = this;
		const pageCount = Math.max(1, _.ctx.store.getState().pageCount);
		const trackWidth = _.scrollbarTrack.getBoundingClientRect().width;
		let thumbWidthPercent = 1 / pageCount * 100;
		if (trackWidth > 0) {
			const minPercent = MIN_THUMB_WIDTH_PX / trackWidth * 100;
			thumbWidthPercent = Math.max(thumbWidthPercent, minPercent);
		}
		thumbWidthPercent = Math.max(0, Math.min(100, thumbWidthPercent));
		_.#thumbWidthPercent = thumbWidthPercent;
		_.#maxTravelPercent = Math.max(0, 100 - thumbWidthPercent);
		_.scrollbarThumb.style.width = `${thumbWidthPercent}%`;
		_.scrollbarGhost.style.width = `${thumbWidthPercent}%`;
	}
	updateThumbPosition(percent) {
		this.scrollbarThumb.style.left = `${percent * this.#maxTravelPercent}%`;
	}
	activateGhost() {
		this.scrollbarGhost.classList.add("tarot-scrollbar-ghost--active");
	}
	deactivateGhost() {
		const _ = this;
		_.scrollbarGhost.classList.remove("tarot-scrollbar-ghost--active");
		_.scrollbarGhost.style.left = "-200%";
	}
	updatePortalForward(loopProgress) {
		const _ = this;
		_.scrollbarThumb.style.left = `${_.#maxTravelPercent + loopProgress * _.#thumbWidthPercent}%`;
		_.scrollbarGhost.style.left = `${(loopProgress - 1) * _.#thumbWidthPercent}%`;
	}
	updatePortalBackward(loopProgress) {
		const _ = this;
		_.scrollbarThumb.style.left = `${-loopProgress * _.#thumbWidthPercent}%`;
		_.scrollbarGhost.style.left = `${_.#maxTravelPercent + (1 - loopProgress) * _.#thumbWidthPercent}%`;
	}
	updateAriaValues() {
		const _ = this;
		const state = _.ctx.store.getState();
		_.scrollbarThumb.setAttribute("aria-valuemax", Math.max(0, state.pageCount - 1));
		_.scrollbarThumb.setAttribute("aria-valuenow", state.pageIndex);
		_.scrollbarThumb.setAttribute("aria-label", `Page ${state.pageIndex + 1} of ${state.pageCount}`);
	}
	handleTouchStart(event) {
		if (event.target.closest(".tarot-scrollbar-thumb") || event.target.closest(".tarot-scrollbar-ghost")) event.preventDefault();
	}
	handleTouchMove(event) {
		if (this.isDragging) event.preventDefault();
	}
	#percentToDragCoord(percent, travelWidth, overflowWidth) {
		if (percent > 1) return travelWidth + (percent - 1) * overflowWidth;
		if (percent < 0) return percent * overflowWidth;
		return percent * travelWidth;
	}
	#dragCoordToPercent(coord, travelWidth, overflowWidth) {
		if (coord > travelWidth) return 1 + (coord - travelWidth) / overflowWidth;
		if (coord < 0) return coord / overflowWidth;
		return coord / travelWidth;
	}
	#getNearestPageForPercent(percent, state) {
		const pageCount = Math.max(1, state.pageCount);
		const lastPage = Math.max(0, pageCount - 1);
		if (pageCount <= 1) return 0;
		if (state.canLoop && percent < 0) return Math.min(1, Math.max(0, Math.abs(percent))) >= .5 ? lastPage : 0;
		if (state.canLoop && percent > 1) return Math.min(1, Math.max(0, percent - 1)) >= .5 ? 0 : lastPage;
		return Math.round(Math.max(0, Math.min(1, percent)) * lastPage);
	}
	startDrag(event) {
		const _ = this;
		const thumb = event.target.closest(".tarot-scrollbar-thumb");
		const ghost = event.target.closest(".tarot-scrollbar-ghost");
		if (!thumb && !ghost) return;
		event.preventDefault();
		event.stopPropagation();
		const grabTarget = thumb || ghost;
		_.activePointerId = typeof event.pointerId === "number" ? event.pointerId : null;
		_.#didMeaningfulDrag = false;
		let trackPercent = _.ctx.store.getAnimation().trackPercent;
		const state = _.ctx.store.getState();
		const pageCount = Math.max(1, state.pageCount);
		const snap = _.ctx.store.getOptions().snap || "page";
		_.isDragging = true;
		if (snap !== "none" && state.canLoop && pageCount > 1 && (trackPercent > 1 || trackPercent < 0)) {
			const lastPage = pageCount - 1;
			let targetPage = 0;
			if (trackPercent > 1) targetPage = ghost ? 0 : lastPage;
			else targetPage = ghost ? lastPage : 0;
			_.ctx.commands.jumpToPage(targetPage);
			trackPercent = _.ctx.store.getAnimation().trackPercent;
			_.syncToTrackPercent(trackPercent);
		}
		_.dragStartX = event.clientX;
		_.dragStartPercent = trackPercent;
		_.#targetPercent = trackPercent;
		_.#lastSyncedPercent = -1;
		_.pointerCaptureTarget = grabTarget;
		grabTarget.setPointerCapture(event.pointerId);
		document.addEventListener("pointermove", _.handlers.pointerMove);
		document.addEventListener("pointerup", _.handlers.pointerUp);
		document.addEventListener("pointercancel", _.handlers.pointerCancel);
		_.scrollbarContainer.classList.add("tarot-scrollbar--dragging");
		_.ctx.emitter.emit(_.ctx.events.user.interacted, {
			via: "scrollbar",
			event
		});
		_.#rafId = requestAnimationFrame(() => _.#tick());
	}
	handleDrag(event) {
		const _ = this;
		if (!_.isDragging) return;
		if (_.activePointerId !== null && event.pointerId !== _.activePointerId) return;
		event.preventDefault();
		const trackRect = _.scrollbarTrack.getBoundingClientRect();
		const travelWidth = trackRect.width * (_.#maxTravelPercent / 100);
		const overflowWidth = trackRect.width * (_.#thumbWidthPercent / 100);
		if (travelWidth <= 0 || overflowWidth <= 0) return;
		const deltaX = event.clientX - _.dragStartX;
		if (!_.#didMeaningfulDrag && Math.abs(deltaX) > DRAG_CLICK_THRESHOLD_PX) _.#didMeaningfulDrag = true;
		const dragCoord = _.#percentToDragCoord(_.dragStartPercent, travelWidth, overflowWidth) + deltaX;
		const rawPercent = _.#dragCoordToPercent(dragCoord, travelWidth, overflowWidth);
		const newPercent = _.ctx.store.getState().canLoop ? rawPercent : Math.max(0, Math.min(1, rawPercent));
		_.#targetPercent = newPercent;
		_.syncToTrackPercent(newPercent);
	}
	handleLostPointerCapture(event) {
		const _ = this;
		if (!_.isDragging) return;
		if (_.activePointerId !== null && event.pointerId !== _.activePointerId) return;
		_.endDrag(event);
	}
	#removeDocumentDragListeners() {
		const _ = this;
		document.removeEventListener("pointermove", _.handlers.pointerMove);
		document.removeEventListener("pointerup", _.handlers.pointerUp);
		document.removeEventListener("pointercancel", _.handlers.pointerCancel);
	}
	#releasePointerCapture(pointerId) {
		const _ = this;
		const id = typeof pointerId === "number" ? pointerId : _.activePointerId;
		if (id === null) return;
		try {
			const target = _.pointerCaptureTarget || _.scrollbarThumb;
			if (target && target.hasPointerCapture(id)) target.releasePointerCapture(id);
		} catch {}
		_.pointerCaptureTarget = null;
	}
	#tick() {
		const _ = this;
		if (!_.isDragging) return;
		if (_.#targetPercent !== _.#lastSyncedPercent) {
			_.ctx.commands.driveTrackPosition({ positionPercent: _.#targetPercent });
			_.#lastSyncedPercent = _.#targetPercent;
		}
		_.#rafId = requestAnimationFrame(() => _.#tick());
	}
	endDrag(event) {
		const _ = this;
		if (!_.isDragging) return;
		if (_.activePointerId !== null && event?.pointerId !== void 0 && event.pointerId !== _.activePointerId) return;
		_.isDragging = false;
		_.#lastDragEndTs = performance.now();
		if (_.#rafId !== null) {
			cancelAnimationFrame(_.#rafId);
			_.#rafId = null;
		}
		if (_.#targetPercent !== _.#lastSyncedPercent) _.ctx.commands.driveTrackPosition({ positionPercent: _.#targetPercent });
		_.#removeDocumentDragListeners();
		_.#releasePointerCapture(event?.pointerId);
		_.activePointerId = null;
		_.scrollbarContainer.classList.remove("tarot-scrollbar--dragging");
		const snap = _.ctx.store.getOptions().snap || "page";
		if (snap === "page") {
			const state = _.ctx.store.getState();
			const nearestPage = _.#getNearestPageForPercent(_.#targetPercent, state);
			_.ctx.commands.goToPage(nearestPage);
		} else if (snap === "slide") _.ctx.commands.driveTrackPosition({ movementType: "settle" });
	}
	handleTrackClick(event) {
		const _ = this;
		if (event.target.closest(".tarot-scrollbar-thumb") || event.target.closest(".tarot-scrollbar-ghost")) return;
		const elapsedSinceDragEnd = performance.now() - _.#lastDragEndTs;
		if (_.#didMeaningfulDrag) {
			_.#didMeaningfulDrag = false;
			if (elapsedSinceDragEnd <= DRAG_CLICK_SUPPRESSION_MS) {
				event.preventDefault();
				event.stopPropagation();
				return;
			}
		}
		event.preventDefault();
		event.stopPropagation();
		const trackRect = _.scrollbarTrack.getBoundingClientRect();
		if (trackRect.width <= 0) return;
		const pageCount = _.ctx.store.getState().pageCount;
		if (pageCount <= 1) return;
		const clickPercent = Math.max(0, Math.min(1, (event.clientX - trackRect.left) / trackRect.width));
		const nearestPage = Math.round(clickPercent * (pageCount - 1));
		_.ctx.emitter.emit(_.ctx.events.user.interacted, {
			via: "scrollbar",
			event
		});
		_.ctx.commands.goToPage(nearestPage);
	}
	handleKeyDown(event) {
		const _ = this;
		if (![
			"ArrowLeft",
			"ArrowRight",
			"Home",
			"End"
		].includes(event.key)) return;
		event.preventDefault();
		event.stopPropagation();
		const state = _.ctx.store.getState();
		let newPage = state.pageIndex;
		switch (event.key) {
			case "ArrowRight":
				if (state.canLoop && state.pageIndex >= state.pageCount - 1) newPage = 0;
				else newPage = Math.min(state.pageCount - 1, state.pageIndex + 1);
				break;
			case "ArrowLeft":
				if (state.canLoop && state.pageIndex <= 0) newPage = state.pageCount - 1;
				else newPage = Math.max(0, state.pageIndex - 1);
				break;
			case "Home":
				newPage = 0;
				break;
			case "End": newPage = state.pageCount - 1;
		}
		_.ctx.emitter.emit(_.ctx.events.user.interacted, {
			via: "key",
			event
		});
		_.ctx.commands.goToPage(newPage);
	}
	show() {
		this.scrollbarContainer.style.display = "";
	}
	hide() {
		this.scrollbarContainer.style.display = "none";
	}
	/** stop an in-flight drag: rAF loop, document listeners and pointer capture */
	stopDrag() {
		const _ = this;
		_.isDragging = false;
		if (_.#rafId !== null) {
			cancelAnimationFrame(_.#rafId);
			_.#rafId = null;
		}
		_.#removeDocumentDragListeners();
		_.#releasePointerCapture();
		_.activePointerId = null;
		_.pointerCaptureTarget = null;
	}
	/** remove plugin-created DOM, leaving an author-supplied container intact */
	removeDOM() {
		const _ = this;
		if (!_.scrollbarContainer) return;
		if (_.scrollbarTrack && _.scrollbarTrack.parentNode === _.scrollbarContainer) _.scrollbarTrack.remove();
		else _.removeOwnedTrackNodes();
		if (_.isAutoGenerated && _.scrollbarContainer.parentNode === _.ctx.carousel) _.ctx.carousel.removeChild(_.scrollbarContainer);
		else {
			_.scrollbarContainer.classList.remove("tarot-scrollbar", "tarot-scrollbar--dragging");
			if (_.scrollbarContainer.style.display === "none") _.scrollbarContainer.style.removeProperty("display");
		}
		_.scrollbarContainer = null;
		_.scrollbarTrack = null;
		_.scrollbarThumb = null;
		_.scrollbarGhost = null;
		_.isAutoGenerated = false;
	}
	destroy() {
		const _ = this;
		_.unmount();
		_.enabled = false;
		_.ctx.emitter.off(_.ctx.events.store.optionsChanged, _.handlers.optionsChanged);
	}
};
if (typeof window !== "undefined") (window.TarotPluginQueue = window.TarotPluginQueue || []).push({
	pluginName: "scrollbar",
	plugin: Scrollbar
});
//#endregion
export { Scrollbar as default };

//# sourceMappingURL=scrollbar.esm.js.map